name: Continuous integration
on: pull_request
jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version-file: '.node-version'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    - uses: mymindstorm/setup-emsdk@6ab9eb1bda2574c4ddb79809fc9247783eaf9021 # v14
      with:
        version: 3.1.61
        actions-cache-folder: 'emsdk-cache'
    - name: Poop out node info
      run: which node && node --version && npm --version
    - name: Install apt deps
      run: sudo apt-get install clang-format ninja-build
    - name: Install npm deps
      run: npm ci
    - name: pre-lib node info
      run: which node && node --version && npm --version
    - name: Build library
      run: make lib
    - name: post-lib node info
      run: which node && node --version && npm --version
    - name: Typecheck
      run: make typecheck
    - name: Check formatting
      run: make checkformat
    - name: Mode node info
      run: which node && node --version && npm --version
    - name: Run tests
      run: make test
